module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        basewhite: "var(--basewhite)",
        black: "var(--black)",
        "blue-light50": "var(--blue-light50)",
        "blue-light700": "var(--blue-light700)",
        "gray-100": "var(--gray-100)",
        "gray-200": "var(--gray-200)",
        "gray-300": "var(--gray-300)",
        "gray-400": "var(--gray-400)",
        "gray-500": "var(--gray-500)",
        "gray-600": "var(--gray-600)",
        "gray-800": "var(--gray-800)",
        "gray-900": "var(--gray-900)",
        "gray-blue50": "var(--gray-blue50)",
        "gray-blue700": "var(--gray-blue700)",
        "indigo-50": "var(--indigo-50)",
        "indigo-700": "var(--indigo-700)",
        "pink-50": "var(--pink-50)",
        "pink-700": "var(--pink-700)",
        "primary-300": "var(--primary-300)",
        "primary-50": "var(--primary-50)",
        "primary-500": "var(--primary-500)",
        "primary-700": "var(--primary-700)",
        "primary-950": "var(--primary-950)",
        "ros-50": "var(--ros-50)",
        "ros-700": "var(--ros-700)",
        "success-50": "var(--success-50)",
        "success-700": "var(--success-700)",
        "text-black": "var(--text-black)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "text-2xl-font-bold": "var(--text-2xl-font-bold-font-family)",
        "text-2xl-font-semibold": "var(--text-2xl-font-semibold-font-family)",
        "text-3xl-font-semibold": "var(--text-3xl-font-semibold-font-family)",
        "text-4xl-font-bold": "var(--text-4xl-font-bold-font-family)",
        "text-4xl-font-semibold": "var(--text-4xl-font-semibold-font-family)",
        "text-base-font-medium": "var(--text-base-font-medium-font-family)",
        "text-base-font-normal": "var(--text-base-font-normal-font-family)",
        "text-lg-font-medium": "var(--text-lg-font-medium-font-family)",
        "text-lg-font-normal": "var(--text-lg-font-normal-font-family)",
        "text-md-regular": "var(--text-md-regular-font-family)",
        "text-md-semibold": "var(--text-md-semibold-font-family)",
        "text-sm-font-medium": "var(--text-sm-font-medium-font-family)",
        "text-sm-font-normal": "var(--text-sm-font-normal-font-family)",
        "text-sm-medium": "var(--text-sm-medium-font-family)",
        "text-sm-regular": "var(--text-sm-regular-font-family)",
        "text-xl-font-medium": "var(--text-xl-font-medium-font-family)",
        "text-xl-font-normal": "var(--text-xl-font-normal-font-family)",
        "text-xs-font-medium": "var(--text-xs-font-medium-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "background-blur-sm": "var(--background-blur-sm)",
        "shadow-xs": "var(--shadow-xs)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
